* 3.0.0
- Rewrite to use typer instead of argparse (user-facing benefit is slightly nicer help text and shell completions)

** Breaking Changes
- New minimum Python 3.7 requirement
- The =--length= option now applies to all text (including before, after, and padding text).  The "visual" length of the printed text is now correctly fixed and will not change even if the padding changes.  While this is a breaking change in behavior, old zscroll commands will still function.  However, some users may wish to increase the =--length= they are using.
- Which options can be changed with =--match-text= are now limited and explicitly specified in the documentation.  Some options would not make sense to set locally or would require special handling.  For example, =-n= is normally set depending on where zscroll is running (terminal or specific panel), and I cannot think of a case where it would make sense to dynamically change this behavior.

** New Functionality
- =-m ".*" <options>= will just check command success instead of search for text
- Add =-C / =--shift-count= to shift the text a certain number of times before exiting (partially addresses #21)

* 2.0.1
** Bug Fixes
- Remove dependency on deprecated distutils

* 2.0.0
** Breaking Changes
- Long options are now hyphenated (e.g. =--update-check=)
- All boolean options take an argument (e.g. =--scroll false=)
- Newlines will be used by default (=--newline= defaults to true) as zscroll's primary use case is for panels, and this behavior is necessary for scrolling to work with polybar and lemonbar.
- =-m= / =-M= syntax has changed to eliminate the previous complicated rules
- The =-f= and =-c= flags have been removed. I don't see them as having a legitimate use case (the default behavior for handling fullwidth characters is much saner), but if anyone would like them back, feel free to make an issue. =-c= would count fullwidth characters as length 1, causing the scrolling text length to change. =-f= would convert all letters to fullwidth if any fullwidth letters were found.

** New Functionality
- Add =-t= / =--timeout= to exit after some timeout
- Add =-r= / =--reverse= to reverse scroll direction
- Add =-U= / =--update-interval= to specify time to wait before running update checking commands
- Add =-e= / =--eval-in-shell= to evaluate commands in a shell (to allow things like subshells, piping, etc.)

** Bug Fixes
- Fix =-p= / =--scroll-padding= (see #4)
- Don't exit if a shell command fails (e.g. mpd has not yet started but will later)

** Miscellaneous
- Add tests and CI
- Change license to GPL3
