.\" Manpage for zscroll.
.\" Contact <nocturnalartifice[at]gmail[dot]com> to correct errors or typos.
.TH ZSCROLL 1 "11 MARCH 2015" "zscroll 0.1" "zscroll man page"
.SH NAME
zscroll \- scroll text for panels
.SH SYNOPSIS
zscroll [-hncf] [-l length] [-b beforetext] [-a aftertext] [-d delay] [scrolltext]
.SH DESCRIPTION
Zscroll is used to create continuously scrolling text.
.SH OPTIONS
.TP
\fB\-h\fR, \fB \-\-help\fR
Print help text.
.TP
\fB\-l\fR, \fB \-\-length\fR
Specify a character length for the text to be scrolled in. If the text given is less than this length, zscroll will not scroll it but just print in place. (default: 40)
.TP
\fB\-b\fR, \fB \-\-beforetext\fR
Specify padding text that will always be displayed to the left of the scrolling section. (default: "")
.TP
\fB\-a\fR, \fB \-\-aftertext\fR
Specify padding text that will always be displayed to the right of the scrolling section. (default: "")
.TP
\fB\-d\fR, \fB \-\-delay\fR
Specify the delay between scroll steps. (default: 0.4)
.TP
\fB\-n\fR, \fB \-\-newline\fR
Add a newline after every update/step. (default: false)
.TP
\fB\-c\fR, \fB \-\-characterlength\fR
By default, zscroll will count full width characters (e.g. Japanese and Chinese characters) as length two since with fixed-width fonts these characters will be twice as long as normal letters. This prevents a bug where the visual length of the scrolling text will become larger when full width characters appear, leaving characters left over and stuck at the end where the full width characters used to be. This option disables this behaviour and will determine length by character count instead. (default: false)
.TP
\fB\-f\fR, \fB \-\-fullwidth\fR
This option provides a different way of dealing with fullwidth characters. If fullwidth characters are detected in the string to be scrolled, it will convert normal ascii characters to the fullwidth equivalents, making all characters to be equal width. This may make the characters look uglier, but it will result in a more visually consistent scroll speed. This cannot be used with the '-c' option or it will have no effect. Also note that all characters will be counted as visual length two, so if the '-l' argument is an odd number, the scrolling text will be the same as if the '-l' was one less. (default: false)
.SH EXAMPLES
Scroll currently playing mpd song with mpc:
.br
$ zscroll -b "playing: " "$(mpc current) - "
.br

You can also pipe into zscroll:
.br
$ xtitle | zscroll -l 60
.SH SEE ALSO
bar(1)
.SH BUGS
If you encounter any bugs, please make an issue on the github page.
.SH AUTHOR
Lit Wakefield <nocturnalartifice[at]gmail[dot]com>
.br
Source: https://github.com/angelic-sedition/zscroll
